# Роли пользователей
ROLE_USER = "user"
ROLE_EMPLOYEE = "employee"
ROLE_MAX_LENGTH = 20

# Лимиты полей
FULL_NAME_MAX_LENGTH = 255
LOGIN_MAX_LENGTH = 255
PHONE_MAX_LENGTH = 20
TELEGRAM_MAX_LENGTH = 255
PASSWORD_HASH_MAX_LENGTH = 255

# Валидация пароля
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 64

# Статусы заявки
APPLICATION_STATUS_IN_QUEUE = "in_queue"
APPLICATION_STATUS_AUTO_APPROVED = "auto_approved"
APPLICATION_STATUS_AUTO_REJECTED = "auto_rejected"
APPLICATION_STATUS_EMPLOYEE_APPROVED = "employee_approved"
APPLICATION_STATUS_EMPLOYEE_REJECTED = "employee_rejected"
APPLICATION_STATUS_MAX_LENGTH = 32

# Лимиты полей заявки
AMOUNT_PRECISION = 12
AMOUNT_SCALE = 2
PURPOSE_MAX_LENGTH = 1024
TELEGRAM_CHANNEL_MAX_LENGTH = 255

# Оценка скоринга (0–100)
SCORE_MIN = 0
SCORE_MAX = 100

# Психологический портрет (метрики 0–10)
PORTRAIT_METRIC_MIN = 0
PORTRAIT_METRIC_MAX = 10
